- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup
      name: myVnet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: myResourceGroup
      allocation_method: Static
      name: myWinPublicIP
    register: output_ip_address

  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"

  - name: Create Network Security Group that allows RDP
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1002
          direction: Inbound

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup
      name: myWinNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myWinPublicIP
      security_group: myNetworkSecurityGroup

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myWinVM
      os_type: Windows
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: R3dh4t1!
      network_interfaces: myWinNIC
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2012-R2-Datacenter'
        version: latest
